/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import sanity.nil.meta.db.Keys;
import sanity.nil.meta.db.MetadataDb;
import sanity.nil.meta.db.tables.Users.UsersPath;
import sanity.nil.meta.db.tables.Workspaces.WorkspacesPath;
import sanity.nil.meta.db.tables.records.UserWorkspacesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserWorkspaces extends TableImpl<UserWorkspacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>metadata_db.user_workspaces</code>
     */
    public static final UserWorkspaces USER_WORKSPACES = new UserWorkspaces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserWorkspacesRecord> getRecordType() {
        return UserWorkspacesRecord.class;
    }

    /**
     * The column <code>metadata_db.user_workspaces.user_id</code>.
     */
    public final TableField<UserWorkspacesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>metadata_db.user_workspaces.ws_id</code>.
     */
    public final TableField<UserWorkspacesRecord, Long> WS_ID = createField(DSL.name("ws_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>metadata_db.user_workspaces.role</code>.
     */
    public final TableField<UserWorkspacesRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>metadata_db.user_workspaces.joined_at</code>.
     */
    public final TableField<UserWorkspacesRecord, OffsetDateTime> JOINED_AT = createField(DSL.name("joined_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private UserWorkspaces(Name alias, Table<UserWorkspacesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserWorkspaces(Name alias, Table<UserWorkspacesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>metadata_db.user_workspaces</code> table
     * reference
     */
    public UserWorkspaces(String alias) {
        this(DSL.name(alias), USER_WORKSPACES);
    }

    /**
     * Create an aliased <code>metadata_db.user_workspaces</code> table
     * reference
     */
    public UserWorkspaces(Name alias) {
        this(alias, USER_WORKSPACES);
    }

    /**
     * Create a <code>metadata_db.user_workspaces</code> table reference
     */
    public UserWorkspaces() {
        this(DSL.name("user_workspaces"), null);
    }

    public <O extends Record> UserWorkspaces(Table<O> path, ForeignKey<O, UserWorkspacesRecord> childPath, InverseForeignKey<O, UserWorkspacesRecord> parentPath) {
        super(path, childPath, parentPath, USER_WORKSPACES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserWorkspacesPath extends UserWorkspaces implements Path<UserWorkspacesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserWorkspacesPath(Table<O> path, ForeignKey<O, UserWorkspacesRecord> childPath, InverseForeignKey<O, UserWorkspacesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserWorkspacesPath(Name alias, Table<UserWorkspacesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserWorkspacesPath as(String alias) {
            return new UserWorkspacesPath(DSL.name(alias), this);
        }

        @Override
        public UserWorkspacesPath as(Name alias) {
            return new UserWorkspacesPath(alias, this);
        }

        @Override
        public UserWorkspacesPath as(Table<?> alias) {
            return new UserWorkspacesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MetadataDb.METADATA_DB;
    }

    @Override
    public UniqueKey<UserWorkspacesRecord> getPrimaryKey() {
        return Keys.USER_WORKSPACES_PKEY;
    }

    @Override
    public List<ForeignKey<UserWorkspacesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_WORKSPACES__USER_WS_USER, Keys.USER_WORKSPACES__USER_WS_WS);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>metadata_db.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_WORKSPACES__USER_WS_USER, null);

        return _users;
    }

    private transient WorkspacesPath _workspaces;

    /**
     * Get the implicit join path to the <code>metadata_db.workspaces</code>
     * table.
     */
    public WorkspacesPath workspaces() {
        if (_workspaces == null)
            _workspaces = new WorkspacesPath(this, Keys.USER_WORKSPACES__USER_WS_WS, null);

        return _workspaces;
    }

    @Override
    public UserWorkspaces as(String alias) {
        return new UserWorkspaces(DSL.name(alias), this);
    }

    @Override
    public UserWorkspaces as(Name alias) {
        return new UserWorkspaces(alias, this);
    }

    @Override
    public UserWorkspaces as(Table<?> alias) {
        return new UserWorkspaces(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWorkspaces rename(String name) {
        return new UserWorkspaces(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWorkspaces rename(Name name) {
        return new UserWorkspaces(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWorkspaces rename(Table<?> name) {
        return new UserWorkspaces(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces where(Condition condition) {
        return new UserWorkspaces(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWorkspaces where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWorkspaces where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWorkspaces where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWorkspaces where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWorkspaces whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
