/*
 * This file is generated by jOOQ.
 */
package sanity.nil.block.db;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sanity.nil.block.db.tables.Blocks;
import sanity.nil.block.db.tables.Tasks;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BlockDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>block_db</code>
     */
    public static final BlockDb BLOCK_DB = new BlockDb();

    /**
     * The table <code>block_db.blocks</code>.
     */
    public final Blocks BLOCKS = Blocks.BLOCKS;

    /**
     * The table <code>block_db.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * No further instances allowed
     */
    private BlockDb() {
        super("block_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Blocks.BLOCKS,
            Tasks.TASKS
        );
    }
}
