/*
 * This file is generated by jOOQ.
 */
package sanity.nil.block.db;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import sanity.nil.block.db.tables.Blocks;
import sanity.nil.block.db.tables.Tasks;
import sanity.nil.block.db.tables.records.BlocksRecord;
import sanity.nil.block.db.tables.records.TasksRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * block_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BlocksRecord> CONSTRAINT_AD = Internal.createUniqueKey(Blocks.BLOCKS, DSL.name("CONSTRAINT_AD"), new TableField[] { Blocks.BLOCKS.HASH }, true);
    public static final UniqueKey<TasksRecord> CONSTRAINT_690 = Internal.createUniqueKey(Tasks.TASKS, DSL.name("CONSTRAINT_690"), new TableField[] { Tasks.TASKS.ID }, true);
}
