/*
 * This file is generated by jOOQ.
 */
package sanity.nil.block.db;


import sanity.nil.block.db.tables.Blocks;
import sanity.nil.block.db.tables.Tasks;


/**
 * Convenience access to all tables in block_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>block_db.blocks</code>.
     */
    public static final Blocks BLOCKS = Blocks.BLOCKS;

    /**
     * The table <code>block_db.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
