/*
 * This file is generated by jOOQ.
 */
package sanity.nil.block.db.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import sanity.nil.block.db.tables.Blocks;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BlocksRecord extends UpdatableRecordImpl<BlocksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>block_db.blocks.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>block_db.blocks.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>block_db.blocks.hash</code>.
     */
    public void setHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>block_db.blocks.hash</code>.
     */
    public String getHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>block_db.blocks.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>block_db.blocks.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlocksRecord
     */
    public BlocksRecord() {
        super(Blocks.BLOCKS);
    }

    /**
     * Create a detached, initialised BlocksRecord
     */
    public BlocksRecord(OffsetDateTime createdAt, String hash, String status) {
        super(Blocks.BLOCKS);

        setCreatedAt(createdAt);
        setHash(hash);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
