quarkus:
  grpc:
    server:
      host: localhost
      use-separate-server: false
      enable-reflection-service: true
    clients:
      blockService:
        host: ${BLOCK_SERVICE_HOST:localhost}
        port: 8081
  redis:
    hosts:
      - redis://:@${REDIS_HOST:localhost}:6379/0
  hibernate-orm:
    log:
      sql: true
      bind-parameters: true
      format-sql: false
    database:
      default-schema: metadata_db
      generation:
        ~: none
  datasource:
    username: sanity
    password: wordpass
    jdbc:
      url: jdbc:postgresql://${PG_HOST:localhost}:5432/jodrive
    db-kind: postgresql
  flyway:
    migrate-at-start: true
    schemas: metadata_db
  scheduler:
    start-mode: forced
  quartz:
    clustered: true
    store-type: jdbc-cmt
    thread-count: 2
    table-prefix: quartz.QRTZ_
  live-reload:
    enabled: false
  test:
    continuous-testing: DISABLED
  devservices:
    enabled: false
  oidc:
    auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT}/realms/jodrive-realm
    application-type: service
    authentication.scopes: openid profile email
    authentication.user-info-required: true
    token.issued-at-required: false
    token.issuer: any
  http:
    limits:
      max-form-attribute-size: 20M
      max-body-size: 20M
#      max-form-attribute-size: 4096
#      max-body-size: 8192
    port: 8082
    cors:
      ~: true
      origins: /.*/
      methods: GET, OPTIONS, HEAD, PUT, POST, DELETE, PATCH
      headers: origin, accept, authorization, content-type, content-disposition
  arc:
    remove-unused-beans: none
    log-injection-errors: true
  index-dependency:
    shared:
      group-id: sanity.nil
      artifact-id: shared
  log:
    category:
      "io.quarkus.http":
        level: DEBUG
      "quarkus.error":
        level: DEBUG
      "io.quarkus.rest":
        level: DEBUG
      "sanity.nil":
        level: DEBUG
      "io.quarkus.redis":
        level: DEBUG
application:
  scheduler:
    interval: 600
    delete-file:
      pagination: 3
  crypto:
    iv: some_value
    keystore:
      path: keystore_crypto.ks
      password: wordpass
      key:
        alias: super_secret_28_key
        password: worpass_secret
