/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import sanity.nil.meta.db.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MetadataDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>metadata_db</code>
     */
    public static final MetadataDb METADATA_DB = new MetadataDb();

    /**
     * The table <code>metadata_db.file_id_sequence</code>.
     */
    public final FileIdSequence FILE_ID_SEQUENCE = FileIdSequence.FILE_ID_SEQUENCE;

    /**
     * The table <code>metadata_db.file_journal</code>.
     */
    public final FileJournal FILE_JOURNAL = FileJournal.FILE_JOURNAL;

    /**
     * The table <code>metadata_db.links</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>metadata_db.statistics</code>.
     */
    public final Statistics STATISTICS = Statistics.STATISTICS;

    /**
     * The table <code>metadata_db.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>metadata_db.user_statistics</code>.
     */
    public final UserStatistics USER_STATISTICS = UserStatistics.USER_STATISTICS;

    /**
     * The table <code>metadata_db.user_subscriptions</code>.
     */
    public final UserSubscriptions USER_SUBSCRIPTIONS = UserSubscriptions.USER_SUBSCRIPTIONS;

    /**
     * The table <code>metadata_db.user_workspaces</code>.
     */
    public final UserWorkspaces USER_WORKSPACES = UserWorkspaces.USER_WORKSPACES;

    /**
     * The table <code>metadata_db.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>metadata_db.workspace_subscriptions</code>.
     */
    public final WorkspaceSubscriptions WORKSPACE_SUBSCRIPTIONS = WorkspaceSubscriptions.WORKSPACE_SUBSCRIPTIONS;

    /**
     * The table <code>metadata_db.workspaces</code>.
     */
    public final Workspaces WORKSPACES = Workspaces.WORKSPACES;

    /**
     * No further instances allowed
     */
    private MetadataDb() {
        super("metadata_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FileIdSequence.FILE_ID_SEQUENCE,
            FileJournal.FILE_JOURNAL,
            Links.LINKS,
            Statistics.STATISTICS,
            Tasks.TASKS,
            UserStatistics.USER_STATISTICS,
            UserSubscriptions.USER_SUBSCRIPTIONS,
            UserWorkspaces.USER_WORKSPACES,
            Users.USERS,
            WorkspaceSubscriptions.WORKSPACE_SUBSCRIPTIONS,
            Workspaces.WORKSPACES
        );
    }
}
