/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db;


import org.jooq.Configuration;
import org.jooq.Field;
import sanity.nil.meta.db.routines.NextFileId;
import sanity.nil.meta.db.routines.NextHistoryId;


/**
 * Convenience access to all stored procedures and functions in metadata_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>metadata_db.next_file_id</code>
     */
    public static Long nextFileId(
          Configuration configuration
        , Long pWsId
    ) {
        NextFileId f = new NextFileId();
        f.setPWsId(pWsId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>metadata_db.next_file_id</code> as a field.
     */
    public static Field<Long> nextFileId(
          Long pWsId
    ) {
        NextFileId f = new NextFileId();
        f.setPWsId(pWsId);

        return f.asField();
    }

    /**
     * Get <code>metadata_db.next_file_id</code> as a field.
     */
    public static Field<Long> nextFileId(
          Field<Long> pWsId
    ) {
        NextFileId f = new NextFileId();
        f.setPWsId(pWsId);

        return f.asField();
    }

    /**
     * Call <code>metadata_db.next_history_id</code>
     */
    public static Integer nextHistoryId(
          Configuration configuration
        , Long pWsId
    ) {
        NextHistoryId f = new NextHistoryId();
        f.setPWsId(pWsId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>metadata_db.next_history_id</code> as a field.
     */
    public static Field<Integer> nextHistoryId(
          Long pWsId
    ) {
        NextHistoryId f = new NextHistoryId();
        f.setPWsId(pWsId);

        return f.asField();
    }

    /**
     * Get <code>metadata_db.next_history_id</code> as a field.
     */
    public static Field<Integer> nextHistoryId(
          Field<Long> pWsId
    ) {
        NextHistoryId f = new NextHistoryId();
        f.setPWsId(pWsId);

        return f.asField();
    }
}
