/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db;


import sanity.nil.meta.db.tables.*;


/**
 * Convenience access to all tables in metadata_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>metadata_db.file_id_sequence</code>.
     */
    public static final FileIdSequence FILE_ID_SEQUENCE = FileIdSequence.FILE_ID_SEQUENCE;

    /**
     * The table <code>metadata_db.file_journal</code>.
     */
    public static final FileJournal FILE_JOURNAL = FileJournal.FILE_JOURNAL;

    /**
     * The table <code>metadata_db.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>metadata_db.statistics</code>.
     */
    public static final Statistics STATISTICS = Statistics.STATISTICS;

    /**
     * The table <code>metadata_db.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>metadata_db.user_statistics</code>.
     */
    public static final UserStatistics USER_STATISTICS = UserStatistics.USER_STATISTICS;

    /**
     * The table <code>metadata_db.user_subscriptions</code>.
     */
    public static final UserSubscriptions USER_SUBSCRIPTIONS = UserSubscriptions.USER_SUBSCRIPTIONS;

    /**
     * The table <code>metadata_db.user_workspaces</code>.
     */
    public static final UserWorkspaces USER_WORKSPACES = UserWorkspaces.USER_WORKSPACES;

    /**
     * The table <code>metadata_db.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>metadata_db.workspace_subscriptions</code>.
     */
    public static final WorkspaceSubscriptions WORKSPACE_SUBSCRIPTIONS = WorkspaceSubscriptions.WORKSPACE_SUBSCRIPTIONS;

    /**
     * The table <code>metadata_db.workspaces</code>.
     */
    public static final Workspaces WORKSPACES = Workspaces.WORKSPACES;
}
