/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import sanity.nil.meta.db.MetadataDb;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NextHistoryId extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>metadata_db.next_history_id.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>metadata_db.next_history_id.p_ws_id</code>.
     */
    public static final Parameter<Long> P_WS_ID = Internal.createParameter("p_ws_id", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public NextHistoryId() {
        super("next_history_id", MetadataDb.METADATA_DB, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_WS_ID);
    }

    /**
     * Set the <code>p_ws_id</code> parameter IN value to the routine
     */
    public void setPWsId(Long value) {
        setValue(P_WS_ID, value);
    }

    /**
     * Set the <code>p_ws_id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setPWsId(Field<Long> field) {
        setField(P_WS_ID, field);
    }
}
