/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import sanity.nil.meta.db.tables.FileIdSequence;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileIdSequenceRecord extends UpdatableRecordImpl<FileIdSequenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>metadata_db.file_id_sequence.ws_id</code>.
     */
    public void setWsId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadata_db.file_id_sequence.ws_id</code>.
     */
    public Long getWsId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>metadata_db.file_id_sequence.next_id</code>.
     */
    public void setNextId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadata_db.file_id_sequence.next_id</code>.
     */
    public Long getNextId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileIdSequenceRecord
     */
    public FileIdSequenceRecord() {
        super(FileIdSequence.FILE_ID_SEQUENCE);
    }

    /**
     * Create a detached, initialised FileIdSequenceRecord
     */
    public FileIdSequenceRecord(Long wsId, Long nextId) {
        super(FileIdSequence.FILE_ID_SEQUENCE);

        setWsId(wsId);
        setNextId(nextId);
        resetChangedOnNotNull();
    }
}
