/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import sanity.nil.meta.db.tables.Statistics;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StatisticsRecord extends UpdatableRecordImpl<StatisticsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>metadata_db.statistics.id</code>.
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadata_db.statistics.id</code>.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>metadata_db.statistics.quota</code>.
     */
    public void setQuota(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadata_db.statistics.quota</code>.
     */
    public String getQuota() {
        return (String) get(1);
    }

    /**
     * Setter for <code>metadata_db.statistics.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>metadata_db.statistics.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatisticsRecord
     */
    public StatisticsRecord() {
        super(Statistics.STATISTICS);
    }

    /**
     * Create a detached, initialised StatisticsRecord
     */
    public StatisticsRecord(Short id, String quota, String description) {
        super(Statistics.STATISTICS);

        setId(id);
        setQuota(quota);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
