/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import sanity.nil.meta.db.tables.UserWorkspaces;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserWorkspacesRecord extends UpdatableRecordImpl<UserWorkspacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>metadata_db.user_workspaces.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadata_db.user_workspaces.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>metadata_db.user_workspaces.ws_id</code>.
     */
    public void setWsId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadata_db.user_workspaces.ws_id</code>.
     */
    public Long getWsId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>metadata_db.user_workspaces.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>metadata_db.user_workspaces.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>metadata_db.user_workspaces.joined_at</code>.
     */
    public void setJoinedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>metadata_db.user_workspaces.joined_at</code>.
     */
    public OffsetDateTime getJoinedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserWorkspacesRecord
     */
    public UserWorkspacesRecord() {
        super(UserWorkspaces.USER_WORKSPACES);
    }

    /**
     * Create a detached, initialised UserWorkspacesRecord
     */
    public UserWorkspacesRecord(UUID userId, Long wsId, String role, OffsetDateTime joinedAt) {
        super(UserWorkspaces.USER_WORKSPACES);

        setUserId(userId);
        setWsId(wsId);
        setRole(role);
        setJoinedAt(joinedAt);
        resetChangedOnNotNull();
    }
}
