/*
 * This file is generated by jOOQ.
 */
package sanity.nil.meta.db.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import sanity.nil.meta.db.tables.Workspaces;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkspacesRecord extends UpdatableRecordImpl<WorkspacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>metadata_db.workspaces.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadata_db.workspaces.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>metadata_db.workspaces.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadata_db.workspaces.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>metadata_db.workspaces.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>metadata_db.workspaces.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspacesRecord
     */
    public WorkspacesRecord() {
        super(Workspaces.WORKSPACES);
    }

    /**
     * Create a detached, initialised WorkspacesRecord
     */
    public WorkspacesRecord(Long id, String name, String description) {
        super(Workspaces.WORKSPACES);

        setId(id);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
